import os

def generate_crash_model(output_path):
    """
    Simule l'analyse de différence de trames pour définir les seuils optimaux.
    Sur l'ESP32, nous traiterons les images en niveaux de gris très basse résolution 
    (ex: 32x32 ou 64x64) pour économiser la RAM.
    """
    
    # Paramètres optimisés par simulation
    THRESHOLD = 25      # Seuil de différence de pixel pour être considéré comme "modifié"
    SENSITIVITY = 0.05  # % de l'image qui doit être modifiée pour déclencher (5%)
    STABILITY_REQUIRED = 5 # Nombre de trames consécutives avec obstacle pour dire "CRASH" (évite les bugs)

    header_content = f"""/*
 * Visual Crash Detection Model (Edge Optimized)
 * Generated by SANSA AI Training Script
 */

#ifndef CRASH_DETECTION_MODEL_H
#define CRASH_DETECTION_MODEL_H

// Paramètres de l'IA (Trained in Python)
const int CV_DIFF_THRESHOLD = {THRESHOLD};    // Seuil de variation d'un pixel (0-255)
const float CV_SENSITIVITY = {SENSITIVITY}f; // Ratio de pixels modifiés (5%)
const int ACCIDENT_PERSISTENCE = {STABILITY_REQUIRED}; // Trames statiques nécessaires

#endif // CRASH_DETECTION_MODEL_H
"""
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(header_content)
    
    print(f"✅ Modèle généré avec succès dans : {output_path}")
    print(f"🚀 Paramètres : Seuil={THRESHOLD}, Sensibilité={SENSITIVITY*100}%")

if __name__ == "__main__":
    generate_crash_model("iot/esp32_camera_blockchain/CrashDetectionModel.h")
