/*
 * Visual Crash Detection Model (Edge Optimized)
 * Generated by SANSA AI Training Script
 */

#ifndef CRASH_DETECTION_MODEL_H
#define CRASH_DETECTION_MODEL_H

// Paramètres de l'IA (Trained in Python)
const int CV_DIFF_THRESHOLD = 25;    // Seuil de variation d'un pixel (0-255)
const float CV_SENSITIVITY = 0.05f; // Ratio de pixels modifiés (5%)
const int ACCIDENT_PERSISTENCE = 5; // Trames statiques nécessaires

#endif // CRASH_DETECTION_MODEL_H
